module.exports = class ClientEvents
    @WALLET_REFILL_CHANGE_TAB: "client:wallet:refill:change:tab"
    @PRICELIST_PRODUCTS_PAGER: "client:pricelist:products:pager"
    @PRICELIST_CHANGE_TITLE: "client:pricelist:change:title"
    @WALLET_PAYMENT_PAGER: "client:wallet:payment:pager"
    @WALLET_BILLS_PAGER: "client:wallet:bills:pager"
    @PROFILE_CHANGE_EMAIL: "client:profile:change:email"
    @STATISTICS_ITEMS_PAGER: "client:statistics:items:pager"
    @STATISTICS_ITEMS_FILTERED: "client:statistics:items:filtered"
    @SHOP_DETAIL_UPDATE_HEIGHT: "client:shop:detail:updateheight"
